stages:
  - deploy

pdf:
  stage: deploy
  image: alpine:edge
  tags:
    - qinc
  only:
    - main
  script:
    - apk update
    - apk --no-cache add tectonic
    # Restore Tectonic cache from project-local directory
    - mkdir -p ${HOME}/.cache/Tectonic
    - test -d "cache" && cp -r cache/* ${HOME}/.cache/Tectonic/
    # Compile paper
    - mkdir -p build
    - tectonic -X compile --keep-intermediates --keep-logs --outdir build main.tex
    # Save Tectonic cache to project-local directory
    - mkdir -p cache
    - cp -r ${HOME}/.cache/Tectonic/* cache/
    # Copy artifact to repository root
    - cp build/main.pdf phd-thesis.pdf
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - cache/
  artifacts:
    paths:
      - phd-thesis.pdf
    expire_in: 1 day
